name: Docker

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'manual image tag'
        required: true
        default: ''

env:
  TAG: ${{ inputs.version || github.ref_name }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push image
        run: |
          tmpName="image-$RANDOM"
          docker build --tag $tmpName .
          IMAGE_ID=ghcr.io/${{ github.actor }}/tidbyt-proxy

          docker tag $tmpName $IMAGE_ID:${{ env.TAG }}
          docker push $IMAGE_ID:${{ env.TAG }}
      